export function fmtBRL(v: number | null | undefined): string {
  if (v == null) return "—";
  return new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(v);
}

export function fmtPct(v: number | null | undefined, dec = 2): string {
  if (v == null) return "—";
  return v.toFixed(dec).replace(".", ",") + "%";
}

function esc(s: unknown): string {
  return String(s ?? "")
    .replaceAll("&", "&amp;").replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;").replaceAll('"', "&quot;");
}

const HEADER_STYLE = `background:#233853;padding:28px 44px 20px;position:relative;overflow:hidden;-webkit-print-color-adjust:exact;print-color-adjust:exact;`;
const BRAND_MARK = `
  <div style="position:absolute;top:-55px;right:-55px;width:220px;height:220px;border-radius:50%;border:52px solid rgba(196,166,100,0.07);"></div>
  <div style="font-family:Georgia,serif;font-size:26px;font-weight:700;color:#fff;letter-spacing:-0.5px;line-height:1;">MIDLEJ</div>
  <div style="font-size:9px;font-weight:500;color:#C4A664;letter-spacing:4px;margin-top:4px;">CAPITAL</div>
`;
const FOOTER_HTML = (hoje: string) => `
<div style="${HEADER_STYLE.replace("28px 44px 20px", "14px 44px")}display:flex;align-items:center;justify-content:space-between;">
  <div style="font-size:10px;color:rgba(255,255,255,0.65);font-weight:500;">midlejcapital.com.br</div>
  <div style="font-size:7px;color:rgba(255,255,255,0.28);letter-spacing:1.5px;">DOCUMENTO CONFIDENCIAL</div>
  <div style="text-align:right;">
    <div style="font-size:7px;color:rgba(255,255,255,0.38);letter-spacing:1.5px;margin-bottom:2px;">GERADO EM</div>
    <div style="font-size:11px;color:#C4A664;font-weight:600;">${esc(hoje)}</div>
  </div>
</div>`;

const BASE_CSS = `*,*::before,*::after{box-sizing:border-box;margin:0;padding:0;}@page{size:A4 portrait;margin:0;}html,body{width:210mm;-webkit-print-color-adjust:exact!important;print-color-adjust:exact!important;}body{font-family:'DM Sans',sans-serif;background:#fff;color:#233853;}.btn-print{display:inline-block;margin:10px 0 0;padding:9px 16px;background:#233853;color:white;border-radius:8px;font-size:12px;cursor:pointer;border:none;}@media print{.no-print{display:none!important;}}`;

// ─── Simulador de Cessão ───────────────────────────────────────────────────

export function buildPdfHtml(params: Record<string, unknown>, resultado: Record<string, unknown>): string {
  const { valorRecebimento, valorCessao, prazo, taxaOriginacao, taxaFunding, taxaDebenture, identificacao } = params as { valorRecebimento: number; valorCessao: number; prazo: number; taxaOriginacao: number; taxaFunding: number; taxaDebenture: number; identificacao?: string };
  const { desagio, comissaoOriginacao, comissaoFunding, totalFees, montanteDebenture, juroDebenture, totalCusto, lucro, roi, viavel, valorMaxCessao, percentualMaxCessao, projecao } = resultado as { desagio: number; comissaoOriginacao: number; comissaoFunding: number; totalFees: number; montanteDebenture: number; juroDebenture: number; totalCusto: number; lucro: number; roi: number | null; viavel: boolean; valorMaxCessao: number; percentualMaxCessao: number; projecao: Array<{ mes: number; montanteDebenture: number; jurosAcumulados: number; custoTotal: number; lucro: number; viavel: boolean }> };

  const sc = viavel ? "#15803d" : "#dc2626";
  const sb = viavel ? "#dcfce7" : "#fee2e2";
  const se = viavel ? "#86efac" : "#fca5a5";
  const sl = viavel ? "OPERAÇÃO VIÁVEL" : "OPERAÇÃO INVIÁVEL";
  const hoje = new Date().toLocaleDateString("pt-BR", { day: "2-digit", month: "long", year: "numeric" });

  const rowsHtml = projecao.map((p, i) => {
    const bg = i % 2 === 0 ? "#ffffff" : "#FAFAFB";
    const lc = p.viavel ? "#15803d" : "#dc2626";
    const badge = p.mes === prazo ? `<span style="display:inline-block;padding:1px 7px;border-radius:20px;font-size:8px;font-weight:700;background:#233853;color:#C4A664;border:1px solid #C4A664;">Atual</span>` : "";
    return `<tr style="background:${bg};border-bottom:1px solid #F0F1F4;"><td style="padding:6px 10px;font-size:9px;font-weight:600;color:#233853;">${p.mes}${badge ? " " + badge : ""}</td><td style="padding:6px 10px;font-size:9px;font-family:monospace;color:#233853;">${esc(fmtBRL(p.montanteDebenture))}</td><td style="padding:6px 10px;font-size:9px;font-family:monospace;color:#b45309;">${esc(fmtBRL(p.jurosAcumulados))}</td><td style="padding:6px 10px;font-size:9px;font-family:monospace;color:#233853;">${esc(fmtBRL(p.custoTotal))}</td><td style="padding:6px 10px;font-size:9px;font-family:monospace;font-weight:700;color:${lc};">${esc(fmtBRL(p.lucro))}</td></tr>`;
  }).join("");

  return `<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"/><title>Simulação de Cessão${identificacao ? " — " + identificacao : ""}</title><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@300;400;500;600&display=swap" rel="stylesheet"/><style>${BASE_CSS}</style></head><body>
<div style="${HEADER_STYLE}"><div style="display:flex;align-items:flex-start;justify-content:space-between;position:relative;z-index:1;">${BRAND_MARK}<div style="text-align:right;"><div style="font-size:20px;color:#fff;font-weight:600;">Simulação de Cessão</div><div style="font-size:10px;color:rgba(255,255,255,0.42);margin-top:3px;">Projeção de Viabilidade — Direito Creditório</div><div style="margin-top:7px;display:inline-flex;align-items:center;gap:6px;background:rgba(196,166,100,0.14);border:1px solid rgba(196,166,100,0.28);border-radius:20px;padding:3px 11px;"><span style="width:5px;height:5px;border-radius:50%;background:#C4A664;display:inline-block;"></span><span style="font-size:8px;font-weight:700;color:#C4A664;letter-spacing:1.5px;">CONFIDENCIAL</span></div></div></div><div style="margin-top:16px;height:1.5px;background:linear-gradient(90deg,#C4A664,rgba(196,166,100,0.08));"></div></div>
<div style="padding:22px 44px;display:flex;flex-direction:column;gap:14px;">
<div class="no-print"><button class="btn-print" onclick="window.print()">Salvar como PDF / Imprimir</button></div>
${identificacao ? `<div style="font-size:13px;font-weight:600;color:#4A5568;border-left:3px solid #C4A664;padding-left:10px;">${esc(identificacao)}</div>` : ""}
<div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;">
<div style="border:1px solid ${se};border-radius:10px;padding:14px 20px;background:${sb};-webkit-print-color-adjust:exact;print-color-adjust:exact;"><div style="font-size:8px;font-weight:600;color:#9AA0B2;letter-spacing:2px;margin-bottom:8px;">STATUS</div><div style="display:flex;align-items:center;gap:8px;"><div style="width:10px;height:10px;border-radius:50%;background:${sc};"></div><span style="font-size:16px;font-weight:700;color:${sc};">${sl}</span></div><div style="margin-top:10px;display:grid;grid-template-columns:1fr 1fr;gap:6px;">${[["Recebimento", fmtBRL(valorRecebimento)], ["Cessão", fmtBRL(valorCessao)], ["Deságio", fmtPct(desagio)], ["Prazo", prazo + " meses"]].map(([k, v]) => `<div><div style="font-size:7.5px;color:#9AA0B2;font-weight:600;text-transform:uppercase;letter-spacing:0.8px;">${esc(k)}</div><div style="font-size:11px;font-weight:700;color:#233853;font-family:monospace;">${esc(v)}</div></div>`).join("")}</div></div>
<div style="border:1px solid #E3E4E7;border-radius:10px;padding:14px 20px;background:#FAFAFB;"><div style="font-size:8px;font-weight:600;color:#9AA0B2;letter-spacing:2px;margin-bottom:8px;">PARÂMETROS</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:6px;">${[["Taxa Originação", fmtPct(taxaOriginacao)], ["Taxa Funding", fmtPct(taxaFunding)], ["Taxa Debênture", fmtPct(taxaDebenture) + "/mês"], ["Prazo", prazo + " meses"]].map(([k, v]) => `<div><div style="font-size:7.5px;color:#9AA0B2;font-weight:600;text-transform:uppercase;letter-spacing:0.8px;">${esc(k)}</div><div style="font-size:11px;font-weight:700;color:#233853;font-family:monospace;">${esc(v)}</div></div>`).join("")}</div></div>
</div>
<div style="border:1px solid #E3E4E7;border-radius:10px;background:#fff;"><div style="padding:10px 18px;border-bottom:1px solid #E3E4E7;background:#FAFAFB;border-radius:10px 10px 0 0;"><div style="font-size:8px;font-weight:700;color:#233853;letter-spacing:1.5px;text-transform:uppercase;">Breakdown de Custos — ${prazo} Meses</div></div><div style="padding:14px 18px;display:grid;grid-template-columns:repeat(3,1fr);gap:10px;">${[["Comissão Originação", fmtBRL(comissaoOriginacao), fmtPct(taxaOriginacao) + " s/ cessão", "#C4A664"], ["Comissão Funding", fmtBRL(comissaoFunding), fmtPct(taxaFunding) + " s/ cessão", "#C4A664"], ["Juros Debênture", fmtBRL(juroDebenture), fmtPct(taxaDebenture) + "/mês × " + prazo + " meses", "#b45309"], ["Total Fees (caixa)", fmtBRL(totalFees), "Originação + Funding", "#4A5568"], ["Montante Debênture", fmtBRL(montanteDebenture), "Principal + Juros", "#4A5568"], ["Custo Total", fmtBRL(totalCusto), "Debênture + Fees", "#233853"]].map(([label, val, sub, color]) => `<div style="border:1px solid #E3E4E7;border-radius:8px;padding:10px 14px;background:#FAFAFB;"><div style="font-size:7.5px;color:#9AA0B2;font-weight:600;text-transform:uppercase;letter-spacing:0.8px;">${esc(label)}</div><div style="font-size:13px;font-weight:700;color:${color};font-family:monospace;margin-top:3px;">${esc(val)}</div><div style="font-size:8px;color:#9AA0B2;margin-top:2px;">${esc(sub)}</div></div>`).join("")}</div></div>
<div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;">
<div style="border:1px solid #E3E4E7;border-top:3px solid ${sc};border-radius:10px;padding:14px 20px;-webkit-print-color-adjust:exact;print-color-adjust:exact;"><div style="font-size:8px;font-weight:600;color:#C4A664;letter-spacing:2px;margin-bottom:8px;">RESULTADO LÍQUIDO</div><div style="font-size:22px;font-weight:700;color:${sc};font-family:monospace;">${esc(fmtBRL(lucro))}</div>${roi != null ? `<div style="font-size:11px;color:#4A5568;margin-top:5px;">ROI sobre fees: <strong style="color:${roi >= 0 ? "#15803d" : "#dc2626"};">${esc(fmtPct(roi))}</strong></div>` : ""}</div>
<div style="border:1px solid #E3E4E7;border-top:3px solid #C4A664;border-radius:10px;padding:14px 20px;"><div style="font-size:8px;font-weight:600;color:#C4A664;letter-spacing:2px;margin-bottom:8px;">MÁX. CESSÃO (BREAK-EVEN)</div><div style="font-size:22px;font-weight:700;color:#233853;font-family:monospace;">${esc(fmtBRL(valorMaxCessao))}</div><div style="font-size:11px;color:#4A5568;margin-top:5px;">${esc(fmtPct(percentualMaxCessao))} do valor de recebimento</div></div>
</div>
<div style="border:1px solid #E3E4E7;border-radius:10px;overflow:hidden;"><div style="padding:10px 18px;border-bottom:1px solid #E3E4E7;background:#FAFAFB;"><div style="font-size:8px;font-weight:700;color:#233853;letter-spacing:1.5px;text-transform:uppercase;">Projeção Mensal</div></div><table style="width:100%;border-collapse:collapse;"><thead><tr style="background:#E9EAEC;border-bottom:1.5px solid #E3E4E7;"><th style="padding:8px 10px;text-align:left;font-size:7.5px;font-weight:600;color:#9AA0B2;text-transform:uppercase;letter-spacing:1px;">Mês</th><th style="padding:8px 10px;text-align:left;font-size:7.5px;font-weight:600;color:#9AA0B2;text-transform:uppercase;letter-spacing:1px;">Montante Debênture</th><th style="padding:8px 10px;text-align:left;font-size:7.5px;font-weight:600;color:#9AA0B2;text-transform:uppercase;letter-spacing:1px;">Juros Acumulados</th><th style="padding:8px 10px;text-align:left;font-size:7.5px;font-weight:600;color:#9AA0B2;text-transform:uppercase;letter-spacing:1px;">Custo Total</th><th style="padding:8px 10px;text-align:left;font-size:7.5px;font-weight:600;color:#9AA0B2;text-transform:uppercase;letter-spacing:1px;">Resultado</th></tr></thead><tbody>${rowsHtml}</tbody></table></div>
</div>
${FOOTER_HTML(hoje)}
</body></html>`;
}

// ─── Simulador de Fundo ────────────────────────────────────────────────────

export function buildPdfFundoHtml(params: Record<string, unknown>, resultado: Record<string, unknown>): string {
  const { capitalDebenture, taxaFunding, taxaDebenture, prazoDebenture, desagio, prazoProcesso, taxaOriginacao } = params as { capitalDebenture: number; taxaFunding: number; taxaDebenture: number; prazoDebenture: number; desagio: number; prazoProcesso: number; taxaOriginacao: number };
  const { feeFunding, capitalDisponivel, nCiclos, mesesOciosos, lucroLiquidoCiclo, lucroTotalCiclos, montanteDebenture: md, jurosDebenture, resultadoLiquido, viavel, roiSobreCapital, ciclos, projecaoMensal } = resultado as { feeFunding: number; capitalDisponivel: number; nCiclos: number; mesesOciosos: number; lucroLiquidoCiclo: number; lucroTotalCiclos: number; montanteDebenture: number; jurosDebenture: number; resultadoLiquido: number; viavel: boolean; roiSobreCapital: number; ciclos: Array<{ numero: number; mesInicio: number; mesFim: number; cessao: number; recebimento: number; originacao: number; lucroLiquido: number; lucroAcumulado: number }>; projecaoMensal: Array<{ mes: number; montanteDebenture: number; jurosAcumulados: number; lucroAcumulado: number; saldo: number; cicloAtivo: number | null; fimCiclo: boolean }> };

  const sc = viavel ? "#15803d" : "#dc2626";
  const sb = viavel ? "#dcfce7" : "#fee2e2";
  const se = viavel ? "#86efac" : "#fca5a5";
  const sl = viavel ? "OPERAÇÃO VIÁVEL" : "OPERAÇÃO INVIÁVEL";
  const hoje = new Date().toLocaleDateString("pt-BR", { day: "2-digit", month: "long", year: "numeric" });

  const ciclosRows = ciclos.map((c, i) => `<tr style="background:${i % 2 === 0 ? "#fff" : "#FAFAFB"};border-bottom:1px solid #F0F1F4;"><td style="padding:6px 10px;font-size:9px;text-align:center;"><span style="display:inline-block;padding:1px 8px;border-radius:20px;font-size:8px;background:#233853;color:#fff;">#${c.numero}</span></td><td style="padding:6px 10px;font-size:9px;color:#9AA0B2;text-align:center;font-family:monospace;">${c.mesInicio}m → ${c.mesFim}m</td><td style="padding:6px 10px;font-size:9px;font-family:monospace;color:#233853;">${esc(fmtBRL(c.cessao))}</td><td style="padding:6px 10px;font-size:9px;font-family:monospace;color:#233853;">${esc(fmtBRL(c.recebimento))}</td><td style="padding:6px 10px;font-size:9px;font-family:monospace;color:#dc2626;">−${esc(fmtBRL(c.originacao))}</td><td style="padding:6px 10px;font-size:9px;font-family:monospace;font-weight:700;color:#15803d;">${esc(fmtBRL(c.lucroLiquido))}</td><td style="padding:6px 10px;font-size:9px;font-family:monospace;font-weight:700;color:#C4A664;">${esc(fmtBRL(c.lucroAcumulado))}</td></tr>`).join("");

  const mensalRows = projecaoMensal.map((p, i) => {
    const isLast = p.mes === prazoDebenture;
    const bg = isLast ? "#233853" : p.fimCiclo ? "#FFFDF7" : i % 2 === 0 ? "#fff" : "#FAFAFB";
    const tc = isLast ? "#fff" : "#233853";
    const sc2 = p.saldo >= 0 ? (isLast ? "#86efac" : "#15803d") : (isLast ? "#fca5a5" : "#dc2626");
    const badge = isLast ? `<span style="display:inline-block;padding:1px 7px;border-radius:20px;font-size:7px;font-weight:700;background:#C4A664;color:#233853;margin-left:4px;">Vencimento</span>` : p.fimCiclo ? `<span style="display:inline-block;padding:1px 7px;border-radius:20px;font-size:7px;font-weight:700;background:#dcfce7;color:#15803d;margin-left:4px;">Recebimento</span>` : "";
    return `<tr style="background:${bg};border-bottom:1px solid #F0F1F4;-webkit-print-color-adjust:exact;print-color-adjust:exact;"><td style="padding:5px 10px;font-size:9px;font-weight:600;color:${tc};">${p.mes}${badge}</td><td style="padding:5px 10px;font-size:9px;color:${isLast ? "rgba(255,255,255,0.5)" : "#9AA0B2"};text-align:center;">${p.cicloAtivo ? "#" + p.cicloAtivo : "—"}</td><td style="padding:5px 10px;font-size:9px;font-family:monospace;color:${tc};">${esc(fmtBRL(p.montanteDebenture))}</td><td style="padding:5px 10px;font-size:9px;font-family:monospace;color:${isLast ? "#fcd34d" : "#b45309"};">${esc(fmtBRL(p.jurosAcumulados))}</td><td style="padding:5px 10px;font-size:9px;font-family:monospace;color:${isLast ? "#86efac" : "#15803d"};">${esc(fmtBRL(p.lucroAcumulado))}</td><td style="padding:5px 10px;font-size:9px;font-family:monospace;font-weight:700;color:${sc2};">${esc(fmtBRL(p.saldo))}</td></tr>`;
  }).join("");

  return `<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"/><title>Simulador de Fundo — Midlej Capital</title><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@300;400;500;600&display=swap" rel="stylesheet"/><style>${BASE_CSS}</style></head><body>
<div style="${HEADER_STYLE}"><div style="display:flex;align-items:flex-start;justify-content:space-between;position:relative;z-index:1;">${BRAND_MARK}<div style="text-align:right;"><div style="font-size:20px;color:#fff;font-weight:600;">Simulador de Fundo</div><div style="font-size:10px;color:rgba(255,255,255,0.42);margin-top:3px;">Debênture + Ciclos de Cessão</div><div style="margin-top:7px;display:inline-flex;align-items:center;gap:6px;background:rgba(196,166,100,0.14);border:1px solid rgba(196,166,100,0.28);border-radius:20px;padding:3px 11px;"><span style="width:5px;height:5px;border-radius:50%;background:#C4A664;display:inline-block;"></span><span style="font-size:8px;font-weight:700;color:#C4A664;letter-spacing:1.5px;">CONFIDENCIAL</span></div></div></div><div style="margin-top:16px;height:1.5px;background:linear-gradient(90deg,#C4A664,rgba(196,166,100,0.08));"></div></div>
<div style="padding:22px 44px;display:flex;flex-direction:column;gap:14px;">
<div class="no-print"><button class="btn-print" onclick="window.print()">Salvar como PDF / Imprimir</button></div>
<div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;">
<div style="border:1px solid ${se};border-radius:10px;padding:14px 20px;background:${sb};-webkit-print-color-adjust:exact;print-color-adjust:exact;"><div style="font-size:8px;font-weight:600;color:#9AA0B2;letter-spacing:2px;margin-bottom:8px;">STATUS</div><div style="display:flex;align-items:center;gap:8px;margin-bottom:10px;"><div style="width:10px;height:10px;border-radius:50%;background:${sc};"></div><span style="font-size:16px;font-weight:700;color:${sc};">${sl}</span></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:6px;">${[["Capital disponível", fmtBRL(capitalDisponivel)], ["Ciclos possíveis", nCiclos + " ciclos"], ["Lucro / ciclo", fmtBRL(lucroLiquidoCiclo)], ["Juros debênture", fmtBRL(jurosDebenture)]].map(([k, v]) => `<div><div style="font-size:7.5px;color:#9AA0B2;font-weight:600;text-transform:uppercase;letter-spacing:0.8px;">${esc(k)}</div><div style="font-size:11px;font-weight:700;color:#233853;font-family:monospace;">${esc(v)}</div></div>`).join("")}</div></div>
<div style="border:1px solid #E3E4E7;border-radius:10px;padding:14px 20px;background:#FAFAFB;"><div style="font-size:8px;font-weight:600;color:#9AA0B2;letter-spacing:2px;margin-bottom:8px;">PARÂMETROS</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:6px;">${[["Capital emitido", fmtBRL(capitalDebenture)], ["Fee funding", fmtPct(taxaFunding) + " (dia 0)"], ["Juro debênture", fmtPct(taxaDebenture) + "/mês"], ["Prazo debênture", prazoDebenture + " meses"], ["Deságio médio", fmtPct(desagio)], ["Prazo / ciclo", prazoProcesso + " meses"], ["Originação/ciclo", fmtPct(taxaOriginacao)], ["Meses ociosos", mesesOciosos + "m"]].map(([k, v]) => `<div><div style="font-size:7.5px;color:#9AA0B2;font-weight:600;text-transform:uppercase;letter-spacing:0.8px;">${esc(k)}</div><div style="font-size:11px;font-weight:700;color:#233853;font-family:monospace;">${esc(v)}</div></div>`).join("")}</div></div>
</div>
<div style="border:1px solid ${se};border-top:3px solid ${sc};border-radius:10px;padding:14px 20px;-webkit-print-color-adjust:exact;print-color-adjust:exact;"><div style="font-size:8px;font-weight:600;color:#9AA0B2;letter-spacing:2px;margin-bottom:10px;">RESULTADO FINAL — ${prazoDebenture} MESES</div><div style="display:flex;align-items:center;gap:10px;"><div style="flex:1;background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;padding:10px 14px;text-align:center;"><div style="font-size:7.5px;color:#16a34a;font-weight:600;text-transform:uppercase;letter-spacing:1px;margin-bottom:4px;">Lucro dos Ciclos</div><div style="font-size:15px;font-weight:700;color:#15803d;font-family:monospace;">${esc(fmtBRL(lucroTotalCiclos))}</div></div><div style="font-size:20px;font-weight:700;color:#D1D5DB;">−</div><div style="flex:1;background:#fff7ed;border:1px solid #fed7aa;border-radius:8px;padding:10px 14px;text-align:center;"><div style="font-size:7.5px;color:#c2410c;font-weight:600;text-transform:uppercase;letter-spacing:1px;margin-bottom:4px;">Juros Debênture</div><div style="font-size:15px;font-weight:700;color:#c2410c;font-family:monospace;">${esc(fmtBRL(jurosDebenture))}</div></div><div style="font-size:20px;font-weight:700;color:#D1D5DB;">=</div><div style="flex:1;border:2px solid ${se};border-radius:8px;padding:10px 14px;text-align:center;background:${sb};-webkit-print-color-adjust:exact;print-color-adjust:exact;"><div style="font-size:7.5px;color:${sc};font-weight:600;text-transform:uppercase;letter-spacing:1px;margin-bottom:4px;">Resultado Líquido</div><div style="font-size:15px;font-weight:700;color:${sc};font-family:monospace;">${esc(fmtBRL(resultadoLiquido))}</div><div style="font-size:8px;color:${sc};margin-top:3px;">${viavel ? "✓ Viável" : "✗ Inviável"} · ROI ${esc(fmtPct(roiSobreCapital))}</div></div></div></div>
<div style="border:1px solid #E3E4E7;border-radius:10px;overflow:hidden;"><div style="padding:10px 18px;border-bottom:1px solid #E3E4E7;background:#FAFAFB;"><div style="font-size:8px;font-weight:700;color:#233853;letter-spacing:1.5px;text-transform:uppercase;">Projeção por Ciclo — Capital base ${esc(fmtBRL(capitalDisponivel))}</div></div><table style="width:100%;border-collapse:collapse;"><thead><tr style="background:#E9EAEC;border-bottom:1.5px solid #E3E4E7;"><th style="padding:7px 10px;text-align:center;font-size:7.5px;font-weight:600;color:#9AA0B2;text-transform:uppercase;letter-spacing:1px;">Ciclo</th><th style="padding:7px 10px;text-align:center;font-size:7.5px;font-weight:600;color:#9AA0B2;text-transform:uppercase;letter-spacing:1px;">Período</th><th style="padding:7px 10px;font-size:7.5px;font-weight:600;color:#9AA0B2;text-transform:uppercase;letter-spacing:1px;">Cessão</th><th style="padding:7px 10px;font-size:7.5px;font-weight:600;color:#9AA0B2;text-transform:uppercase;letter-spacing:1px;">Recebimento</th><th style="padding:7px 10px;font-size:7.5px;font-weight:600;color:#9AA0B2;text-transform:uppercase;letter-spacing:1px;">(−) Originação</th><th style="padding:7px 10px;font-size:7.5px;font-weight:600;color:#9AA0B2;text-transform:uppercase;letter-spacing:1px;">Lucro Líquido</th><th style="padding:7px 10px;font-size:7.5px;font-weight:600;color:#9AA0B2;text-transform:uppercase;letter-spacing:1px;">Acumulado</th></tr></thead><tbody>${ciclosRows}</tbody><tfoot><tr style="background:#233853;-webkit-print-color-adjust:exact;print-color-adjust:exact;"><td colspan="5" style="padding:7px 10px;font-size:9px;font-weight:700;color:#fff;">Total — ${nCiclos} ciclos</td><td style="padding:7px 10px;font-size:9px;font-family:monospace;font-weight:700;color:#86efac;">${esc(fmtBRL(lucroTotalCiclos))}</td><td style="padding:7px 10px;font-size:9px;font-family:monospace;font-weight:700;color:#C4A664;">${esc(fmtBRL(lucroTotalCiclos))}</td></tr></tfoot></table></div>
<div style="border:1px solid #E3E4E7;border-radius:10px;overflow:hidden;"><div style="padding:10px 18px;border-bottom:1px solid #E3E4E7;background:#FAFAFB;"><div style="font-size:8px;font-weight:700;color:#233853;letter-spacing:1.5px;text-transform:uppercase;">Projeção Mensal — Debênture vs. Lucro Acumulado</div></div><table style="width:100%;border-collapse:collapse;"><thead><tr style="background:#E9EAEC;border-bottom:1.5px solid #E3E4E7;"><th style="padding:7px 10px;font-size:7.5px;font-weight:600;color:#9AA0B2;text-transform:uppercase;letter-spacing:1px;">Mês</th><th style="padding:7px 10px;text-align:center;font-size:7.5px;font-weight:600;color:#9AA0B2;text-transform:uppercase;letter-spacing:1px;">Ciclo</th><th style="padding:7px 10px;font-size:7.5px;font-weight:600;color:#9AA0B2;text-transform:uppercase;letter-spacing:1px;">Montante Debênture</th><th style="padding:7px 10px;font-size:7.5px;font-weight:600;color:#9AA0B2;text-transform:uppercase;letter-spacing:1px;">Juros Acum.</th><th style="padding:7px 10px;font-size:7.5px;font-weight:600;color:#9AA0B2;text-transform:uppercase;letter-spacing:1px;">Lucro Acum. Ciclos</th><th style="padding:7px 10px;font-size:7.5px;font-weight:600;color:#9AA0B2;text-transform:uppercase;letter-spacing:1px;">Saldo Projetado</th></tr></thead><tbody>${mensalRows}</tbody><tfoot><tr><td colspan="6" style="height:4px;background:rgba(196,166,100,0.3);-webkit-print-color-adjust:exact;print-color-adjust:exact;"></td></tr></tfoot></table></div>
</div>
${FOOTER_HTML(hoje)}
</body></html>`;
}

// ─── Projeção Anual ────────────────────────────────────────────────────────

export function buildPdfAnualHtml(params: Record<string, unknown>, resultado: Record<string, unknown>): string {
  const { captacaoMensal, taxaFunding, taxaDebenture, horizonte, desagio, prazoProcesso, taxaOriginacao, percentualInutilizavel } = params as { captacaoMensal: number; taxaFunding: number; taxaDebenture: number; horizonte: number; desagio: number; prazoProcesso: number; taxaOriginacao: number; percentualInutilizavel: number };
  const { feeFunding, capitalDisponivel, captacaoEfetiva, capitalOcioso, lucroLiquido, viavelOp, totalCaptado, totalFeeFunding, totalOcioso, totalInvestido, totalLucro, totalOpsCompletadas, roi, meses } = resultado as { feeFunding: number; capitalDisponivel: number; captacaoEfetiva: number; capitalOcioso: number; lucroLiquido: number; viavelOp: boolean; totalCaptado: number; totalFeeFunding: number; totalOcioso: number; totalInvestido: number; totalLucro: number; totalOpsCompletadas: number; roi: number; meses: Array<{ mes: number; efetivo: number; ocioso: number; opsAtivas: number; completou: boolean; recebimentoMes: number; lucroMes: number; lucroAcumulado: number }> };

  const sc = viavelOp ? "#15803d" : "#dc2626";
  const sb = viavelOp ? "#dcfce7" : "#fee2e2";
  const se = viavelOp ? "#86efac" : "#fca5a5";
  const sl = viavelOp ? "OPERAÇÃO VIÁVEL" : "OPERAÇÃO INVIÁVEL";
  const hoje = new Date().toLocaleDateString("pt-BR", { day: "2-digit", month: "long", year: "numeric" });

  const mensalRows = meses.map((m, i) => {
    const isLast = m.mes === horizonte;
    const bg = isLast ? "#233853" : m.completou ? "#FFFDF7" : i % 2 === 0 ? "#fff" : "#FAFAFB";
    const tc = isLast ? "#fff" : "#233853";
    const lColor = m.lucroMes > 0 ? (isLast ? "#86efac" : "#15803d") : (isLast ? "rgba(255,255,255,0.25)" : "#C4C7D0");
    const badge = isLast ? `<span style="display:inline-block;padding:1px 7px;border-radius:20px;font-size:7px;font-weight:700;background:#C4A664;color:#233853;margin-left:4px;">Final</span>` : m.completou ? `<span style="display:inline-block;padding:1px 7px;border-radius:20px;font-size:7px;font-weight:700;background:#dcfce7;color:#15803d;margin-left:4px;">Recebimento</span>` : "";
    return `<tr style="background:${bg};border-bottom:1px solid #F0F1F4;-webkit-print-color-adjust:exact;print-color-adjust:exact;"><td style="padding:5px 10px;font-size:9px;font-weight:600;color:${tc};">${m.mes}${badge}</td><td style="padding:5px 10px;font-size:9px;font-family:monospace;color:${tc};">${esc(fmtBRL(m.efetivo))}</td><td style="padding:5px 10px;font-size:9px;font-family:monospace;color:${isLast ? "#fcd34d" : "#b45309"};">${esc(fmtBRL(m.ocioso))}</td><td style="padding:5px 10px;font-size:9px;text-align:center;font-weight:700;color:${isLast ? "rgba(255,255,255,0.5)" : "#9AA0B2"};">${m.opsAtivas}</td><td style="padding:5px 10px;font-size:9px;font-family:monospace;color:${m.completou ? (isLast ? "#86efac" : "#15803d") : (isLast ? "rgba(255,255,255,0.25)" : "#C4C7D0")};">${m.completou ? esc(fmtBRL(m.recebimentoMes)) : "—"}</td><td style="padding:5px 10px;font-size:9px;font-family:monospace;font-weight:700;color:${lColor};">${m.lucroMes > 0 ? esc(fmtBRL(m.lucroMes)) : "—"}</td><td style="padding:5px 10px;font-size:9px;font-family:monospace;font-weight:700;color:${isLast ? "#C4A664" : "#233853"};">${esc(fmtBRL(m.lucroAcumulado))}</td></tr>`;
  }).join("");

  return `<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"/><title>Projeção Anual — Midlej Capital</title><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@300;400;500;600&display=swap" rel="stylesheet"/><style>${BASE_CSS}</style></head><body>
<div style="${HEADER_STYLE}"><div style="display:flex;align-items:flex-start;justify-content:space-between;position:relative;z-index:1;">${BRAND_MARK}<div style="text-align:right;"><div style="font-size:20px;color:#fff;font-weight:600;">Projeção Anual</div><div style="font-size:10px;color:rgba(255,255,255,0.42);margin-top:3px;">Captação recorrente — ${horizonte} meses</div><div style="margin-top:7px;display:inline-flex;align-items:center;gap:6px;background:rgba(196,166,100,0.14);border:1px solid rgba(196,166,100,0.28);border-radius:20px;padding:3px 11px;"><span style="width:5px;height:5px;border-radius:50%;background:#C4A664;display:inline-block;"></span><span style="font-size:8px;font-weight:700;color:#C4A664;letter-spacing:1.5px;">CONFIDENCIAL</span></div></div></div><div style="margin-top:16px;height:1.5px;background:linear-gradient(90deg,#C4A664,rgba(196,166,100,0.08));"></div></div>
<div style="padding:22px 44px;display:flex;flex-direction:column;gap:14px;">
<div class="no-print"><button class="btn-print" onclick="window.print()">Salvar como PDF / Imprimir</button></div>
<div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;">
<div style="border:1px solid ${se};border-radius:10px;padding:14px 20px;background:${sb};-webkit-print-color-adjust:exact;print-color-adjust:exact;"><div style="font-size:8px;font-weight:600;color:#9AA0B2;letter-spacing:2px;margin-bottom:8px;">STATUS</div><div style="display:flex;align-items:center;gap:8px;margin-bottom:10px;"><div style="width:10px;height:10px;border-radius:50%;background:${sc};"></div><span style="font-size:16px;font-weight:700;color:${sc};">${sl}</span></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:6px;">${[["Captação efetiva/mês", fmtBRL(captacaoEfetiva)], ["Capital ocioso/mês", fmtBRL(capitalOcioso)], ["Lucro por operação", fmtBRL(lucroLiquido)], ["Ops completadas", totalOpsCompletadas + " em " + horizonte + "m"]].map(([k, v]) => `<div><div style="font-size:7.5px;color:#9AA0B2;font-weight:600;text-transform:uppercase;letter-spacing:0.8px;">${esc(k)}</div><div style="font-size:11px;font-weight:700;color:#233853;font-family:monospace;">${esc(v)}</div></div>`).join("")}</div></div>
<div style="border:1px solid #E3E4E7;border-radius:10px;padding:14px 20px;background:#FAFAFB;"><div style="font-size:8px;font-weight:600;color:#9AA0B2;letter-spacing:2px;margin-bottom:8px;">PARÂMETROS</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:6px;">${[["Captação mensal", fmtBRL(captacaoMensal)], ["Fee de funding", fmtPct(taxaFunding) + " (upfront)"], ["Capital disponível/mês", fmtBRL(capitalDisponivel)], ["Capital inutilizável", fmtPct(percentualInutilizavel)], ["Deságio médio", fmtPct(desagio)], ["Prazo / ciclo", prazoProcesso + " meses"], ["Taxa originação", fmtPct(taxaOriginacao)], ["Juro debênture", taxaDebenture > 0 ? fmtPct(taxaDebenture) + "/mês" : "—"]].map(([k, v]) => `<div><div style="font-size:7.5px;color:#9AA0B2;font-weight:600;text-transform:uppercase;letter-spacing:0.8px;">${esc(k)}</div><div style="font-size:11px;font-weight:700;color:#233853;font-family:monospace;">${esc(v)}</div></div>`).join("")}</div></div>
</div>
<div style="border:1px solid #E3E4E7;border-top:3px solid ${sc};border-radius:10px;padding:14px 20px;-webkit-print-color-adjust:exact;print-color-adjust:exact;"><div style="font-size:8px;font-weight:600;color:#9AA0B2;letter-spacing:2px;margin-bottom:10px;">RESULTADO — ${horizonte} MESES</div><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:10px;">${[["Lucro Total", fmtBRL(totalLucro), sc], ["ROI s/ investido", fmtPct(roi), roi >= 0 ? "#15803d" : "#dc2626"], ["Fee funding acum.", fmtBRL(totalFeeFunding), "#dc2626"], ["Capital ocioso acum.", fmtBRL(totalOcioso), "#b45309"]].map(([k, v, c]) => `<div style="border:1px solid #E3E4E7;border-radius:8px;padding:10px 14px;background:#FAFAFB;"><div style="font-size:7.5px;color:#9AA0B2;font-weight:600;text-transform:uppercase;letter-spacing:0.8px;">${esc(k)}</div><div style="font-size:15px;font-weight:700;color:${c};font-family:monospace;margin-top:3px;">${esc(v)}</div></div>`).join("")}</div></div>
<div style="border:1px solid #E3E4E7;border-radius:10px;overflow:hidden;"><div style="padding:10px 18px;border-bottom:1px solid #E3E4E7;background:#FAFAFB;"><div style="font-size:8px;font-weight:700;color:#233853;letter-spacing:1.5px;text-transform:uppercase;">Projeção Mensal — ${horizonte} Meses</div><div style="font-size:8px;color:#9AA0B2;margin-top:2px;">${esc(fmtBRL(captacaoMensal))}/mês · ${esc(fmtPct(percentualInutilizavel))} inutilizável · ciclos de ${prazoProcesso} meses · 1º recebimento no mês ${prazoProcesso + 1}</div></div><table style="width:100%;border-collapse:collapse;"><thead><tr style="background:#E9EAEC;border-bottom:1.5px solid #E3E4E7;"><th style="padding:7px 10px;font-size:7.5px;font-weight:600;color:#9AA0B2;text-transform:uppercase;letter-spacing:1px;">Mês</th><th style="padding:7px 10px;font-size:7.5px;font-weight:600;color:#9AA0B2;text-transform:uppercase;letter-spacing:1px;">Efetivo</th><th style="padding:7px 10px;font-size:7.5px;font-weight:600;color:#9AA0B2;text-transform:uppercase;letter-spacing:1px;">Ocioso</th><th style="padding:7px 10px;text-align:center;font-size:7.5px;font-weight:600;color:#9AA0B2;text-transform:uppercase;letter-spacing:1px;">Ops. Ativas</th><th style="padding:7px 10px;font-size:7.5px;font-weight:600;color:#9AA0B2;text-transform:uppercase;letter-spacing:1px;">Recebimento</th><th style="padding:7px 10px;font-size:7.5px;font-weight:600;color:#9AA0B2;text-transform:uppercase;letter-spacing:1px;">Lucro Mês</th><th style="padding:7px 10px;font-size:7.5px;font-weight:600;color:#9AA0B2;text-transform:uppercase;letter-spacing:1px;">Lucro Acum.</th></tr></thead><tbody>${mensalRows}</tbody><tfoot><tr><td colspan="7" style="height:4px;background:rgba(196,166,100,0.3);-webkit-print-color-adjust:exact;print-color-adjust:exact;"></td></tr></tfoot></table></div>
</div>
${FOOTER_HTML(hoje)}
</body></html>`;
}
